<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>co.edu.escuelaing</groupId>
    <artifactId>arrival-workshop</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>arrival-service</module>
        <module>api-gateway</module>
    </modules>

    <properties>
        <sonar.projectKey>arrivals</sonar.projectKey>
        <sonar.projectName>Arrivals</sonar.projectName>
        <sonar.host.url>https://sonarqube.cglabs.site</sonar.host.url>
        <sonar.sources>pom.xml,docker-compose.yml,README.md</sonar.sources>
        <sonar.sourceEncoding>UTF-8</sonar.sourceEncoding>
    </properties>
</project>
